project_id = "uacuxblipehehknafwep"

[functions.register-postcard]
verify_jwt = false

[functions.assign-postcards]
verify_jwt = false

[functions.generate-qr]
verify_jwt = false

[functions.generate-qr-pdf]
verify_jwt = false
